<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Genres.aspx.cs" Inherits="BookWorld_WEB.Genres" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Жанры</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Код_Жанра" DataSourceID="SqlDataSource1" EmptyDataText="There are no data records to display." AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" PageSize="15">
                <AlternatingRowStyle BackColor="#CCCCCC" />
                <Columns>
                    <asp:BoundField DataField="Код_Жанра" HeaderText="Код_Жанра" ReadOnly="True" SortExpression="Код_Жанра" />
                    <asp:BoundField DataField="Наименование" HeaderText="Наименование" SortExpression="Наименование" />
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:BookWorldDataBaseConnectionString1 %>" DeleteCommand="DELETE FROM [Жанры] WHERE [Код_Жанра] = @Код_Жанра" InsertCommand="INSERT INTO [Жанры] ([Наименование]) VALUES (@Наименование)" ProviderName="<%$ ConnectionStrings:BookWorldDataBaseConnectionString1.ProviderName %>" SelectCommand="SELECT [Код_Жанра], [Наименование] FROM [Жанры]" UpdateCommand="UPDATE [Жанры] SET [Наименование] = @Наименование WHERE [Код_Жанра] = @Код_Жанра">
                <DeleteParameters>
                    <asp:Parameter Name="Код_Жанра" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Наименование" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Наименование" Type="String" />
                    <asp:Parameter Name="Код_Жанра" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <asp:Label ID="Label1" runat="server" Text="Введите название"></asp:Label><br />
            <asp:TextBox ID="TitleTextBox" runat="server"></asp:TextBox><br /><br />
            <asp:Button ID="AddButton" runat="server" Text="Добавить" OnClick="AddButton_Click" />

        </div>
        <div>
            <br /><br /><br />
            <asp:LinkButton ID="BackToDefaultLinkButton" runat="server" OnClick="BackToDefaultLinkButton_Click">Вернуться на главную</asp:LinkButton>
        </div>
    </form>
</body>
</html>
