//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWorld_WEB.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем ПолучитьСправочникТоварыJSONResult из пространства имен http://Microsoft.ServiceModel.Samples не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ПолучитьСправочникТоварыJSON", ReplyAction="*")]
        BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONResponse ПолучитьСправочникТоварыJSON(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ПолучитьСправочникТоварыJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONResponse> ПолучитьСправочникТоварыJSONAsync(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем ПолучитьСправочникТоварыXMLResult из пространства имен http://Microsoft.ServiceModel.Samples не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ПолучитьСправочникТоварыXML", ReplyAction="*")]
        BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLResponse ПолучитьСправочникТоварыXML(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ПолучитьСправочникТоварыXML", ReplyAction="*")]
        System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLResponse> ПолучитьСправочникТоварыXMLAsync(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем smthResult из пространства имен http://Microsoft.ServiceModel.Samples не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/smth", ReplyAction="*")]
        BookWorld_WEB.ServiceReference1.smthResponse smth(BookWorld_WEB.ServiceReference1.smthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/smth", ReplyAction="*")]
        System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.smthResponse> smthAsync(BookWorld_WEB.ServiceReference1.smthRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ПолучитьСправочникТоварыJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ПолучитьСправочникТоварыJSON", Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequestBody Body;
        
        public ПолучитьСправочникТоварыJSONRequest() {
        }
        
        public ПолучитьСправочникТоварыJSONRequest(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ПолучитьСправочникТоварыJSONRequestBody {
        
        public ПолучитьСправочникТоварыJSONRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ПолучитьСправочникТоварыJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ПолучитьСправочникТоварыJSONResponse", Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONResponseBody Body;
        
        public ПолучитьСправочникТоварыJSONResponse() {
        }
        
        public ПолучитьСправочникТоварыJSONResponse(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples")]
    public partial class ПолучитьСправочникТоварыJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ПолучитьСправочникТоварыJSONResult;
        
        public ПолучитьСправочникТоварыJSONResponseBody() {
        }
        
        public ПолучитьСправочникТоварыJSONResponseBody(string ПолучитьСправочникТоварыJSONResult) {
            this.ПолучитьСправочникТоварыJSONResult = ПолучитьСправочникТоварыJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ПолучитьСправочникТоварыXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ПолучитьСправочникТоварыXML", Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequestBody Body;
        
        public ПолучитьСправочникТоварыXMLRequest() {
        }
        
        public ПолучитьСправочникТоварыXMLRequest(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ПолучитьСправочникТоварыXMLRequestBody {
        
        public ПолучитьСправочникТоварыXMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ПолучитьСправочникТоварыXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ПолучитьСправочникТоварыXMLResponse", Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLResponseBody Body;
        
        public ПолучитьСправочникТоварыXMLResponse() {
        }
        
        public ПолучитьСправочникТоварыXMLResponse(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples")]
    public partial class ПолучитьСправочникТоварыXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ПолучитьСправочникТоварыXMLResult;
        
        public ПолучитьСправочникТоварыXMLResponseBody() {
        }
        
        public ПолучитьСправочникТоварыXMLResponseBody(string ПолучитьСправочникТоварыXMLResult) {
            this.ПолучитьСправочникТоварыXMLResult = ПолучитьСправочникТоварыXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="smth", Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public BookWorld_WEB.ServiceReference1.smthRequestBody Body;
        
        public smthRequest() {
        }
        
        public smthRequest(BookWorld_WEB.ServiceReference1.smthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class smthRequestBody {
        
        public smthRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class smthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="smthResponse", Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public BookWorld_WEB.ServiceReference1.smthResponseBody Body;
        
        public smthResponse() {
        }
        
        public smthResponse(BookWorld_WEB.ServiceReference1.smthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples")]
    public partial class smthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string smthResult;
        
        public smthResponseBody() {
        }
        
        public smthResponseBody(string smthResult) {
            this.smthResult = smthResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BookWorld_WEB.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BookWorld_WEB.ServiceReference1.ServiceSoap>, BookWorld_WEB.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONResponse BookWorld_WEB.ServiceReference1.ServiceSoap.ПолучитьСправочникТоварыJSON(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequest request) {
            return base.Channel.ПолучитьСправочникТоварыJSON(request);
        }
        
        public string ПолучитьСправочникТоварыJSON() {
            BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequest inValue = new BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequest();
            inValue.Body = new BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequestBody();
            BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONResponse retVal = ((BookWorld_WEB.ServiceReference1.ServiceSoap)(this)).ПолучитьСправочникТоварыJSON(inValue);
            return retVal.Body.ПолучитьСправочникТоварыJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONResponse> BookWorld_WEB.ServiceReference1.ServiceSoap.ПолучитьСправочникТоварыJSONAsync(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequest request) {
            return base.Channel.ПолучитьСправочникТоварыJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONResponse> ПолучитьСправочникТоварыJSONAsync() {
            BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequest inValue = new BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequest();
            inValue.Body = new BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыJSONRequestBody();
            return ((BookWorld_WEB.ServiceReference1.ServiceSoap)(this)).ПолучитьСправочникТоварыJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLResponse BookWorld_WEB.ServiceReference1.ServiceSoap.ПолучитьСправочникТоварыXML(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequest request) {
            return base.Channel.ПолучитьСправочникТоварыXML(request);
        }
        
        public string ПолучитьСправочникТоварыXML() {
            BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequest inValue = new BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequest();
            inValue.Body = new BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequestBody();
            BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLResponse retVal = ((BookWorld_WEB.ServiceReference1.ServiceSoap)(this)).ПолучитьСправочникТоварыXML(inValue);
            return retVal.Body.ПолучитьСправочникТоварыXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLResponse> BookWorld_WEB.ServiceReference1.ServiceSoap.ПолучитьСправочникТоварыXMLAsync(BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequest request) {
            return base.Channel.ПолучитьСправочникТоварыXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLResponse> ПолучитьСправочникТоварыXMLAsync() {
            BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequest inValue = new BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequest();
            inValue.Body = new BookWorld_WEB.ServiceReference1.ПолучитьСправочникТоварыXMLRequestBody();
            return ((BookWorld_WEB.ServiceReference1.ServiceSoap)(this)).ПолучитьСправочникТоварыXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookWorld_WEB.ServiceReference1.smthResponse BookWorld_WEB.ServiceReference1.ServiceSoap.smth(BookWorld_WEB.ServiceReference1.smthRequest request) {
            return base.Channel.smth(request);
        }
        
        public string smth() {
            BookWorld_WEB.ServiceReference1.smthRequest inValue = new BookWorld_WEB.ServiceReference1.smthRequest();
            inValue.Body = new BookWorld_WEB.ServiceReference1.smthRequestBody();
            BookWorld_WEB.ServiceReference1.smthResponse retVal = ((BookWorld_WEB.ServiceReference1.ServiceSoap)(this)).smth(inValue);
            return retVal.Body.smthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.smthResponse> BookWorld_WEB.ServiceReference1.ServiceSoap.smthAsync(BookWorld_WEB.ServiceReference1.smthRequest request) {
            return base.Channel.smthAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookWorld_WEB.ServiceReference1.smthResponse> smthAsync() {
            BookWorld_WEB.ServiceReference1.smthRequest inValue = new BookWorld_WEB.ServiceReference1.smthRequest();
            inValue.Body = new BookWorld_WEB.ServiceReference1.smthRequestBody();
            return ((BookWorld_WEB.ServiceReference1.ServiceSoap)(this)).smthAsync(inValue);
        }
    }
}
