//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWorld_WEB.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ПолучитьСправочникТоварыJSON", ReplyAction="*")]
        void ПолучитьСправочникТоварыJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ПолучитьСправочникТоварыJSON", ReplyAction="*")]
        System.Threading.Tasks.Task ПолучитьСправочникТоварыJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ПолучитьСправочникТоварыXML", ReplyAction="*")]
        void ПолучитьСправочникТоварыXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ПолучитьСправочникТоварыXML", ReplyAction="*")]
        System.Threading.Tasks.Task ПолучитьСправочникТоварыXMLAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BookWorld_WEB.ServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BookWorld_WEB.ServiceReference.ServiceSoap>, BookWorld_WEB.ServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ПолучитьСправочникТоварыJSON() {
            base.Channel.ПолучитьСправочникТоварыJSON();
        }
        
        public System.Threading.Tasks.Task ПолучитьСправочникТоварыJSONAsync() {
            return base.Channel.ПолучитьСправочникТоварыJSONAsync();
        }
        
        public void ПолучитьСправочникТоварыXML() {
            base.Channel.ПолучитьСправочникТоварыXML();
        }
        
        public System.Threading.Tasks.Task ПолучитьСправочникТоварыXMLAsync() {
            return base.Channel.ПолучитьСправочникТоварыXMLAsync();
        }
    }
}
